version: "3.9"
services:
  web:
    init: true
    restart: unless-stopped
    image: homebot:latest
    network_mode: "host"
    privileged: true
    volumes:
      - ./server_logs:/server_logs
    command: python3 server.py
